// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Repository;

#nullable disable

namespace Shop.Repository.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20240730133154_mig8")]
    partial class mig8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Entity.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Shop.Entity.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Shop.Entity.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3819),
                            IsDeleted = false,
                            Name = "Electronics",
                            Path = "electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3831),
                            IsDeleted = false,
                            Name = "Books",
                            Path = "books"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3832),
                            IsDeleted = false,
                            Name = "Clothing",
                            Path = "clothing"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3833),
                            IsDeleted = false,
                            Name = "Home & Kitchen",
                            Path = "home-kitchen"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3834),
                            IsDeleted = false,
                            Name = "Toys",
                            Path = "toys"
                        });
                });

            modelBuilder.Entity("Shop.Entity.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3953),
                            Description = "Latest smartphone",
                            Image = "https://cdn.cimri.io/pictures/article/original/48/48330.jpg",
                            IsDeleted = false,
                            Price = 699m,
                            Quantity = 10,
                            Title = "Iphone 15"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3956),
                            Description = "High performance laptop",
                            Image = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/apple/thumb/114754-1-2_large.jpg",
                            IsDeleted = false,
                            Price = 999m,
                            Quantity = 10,
                            Title = "Macbook air m1"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3957),
                            Description = "Interesting fiction book",
                            Image = "https://m.media-amazon.com/images/I/B1SgARaaNFL._AC_UF1000,1000_QL80_.jpg",
                            IsDeleted = false,
                            Price = 19m,
                            Quantity = 10,
                            Title = "The Host"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3959),
                            Description = "Informative science book",
                            Image = "https://m.media-amazon.com/images/I/51E2055ZGUL._AC_UF1000,1000_QL80_.jpg",
                            IsDeleted = false,
                            Price = 29m,
                            Quantity = 10,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3960),
                            Description = "Comfortable cotton t-shirt",
                            Image = "https://st-tommy.mncdn.com/mnpadding/1000/1335/FFFFFF/Content/media/ProductImg/original/638225199873500935.webp",
                            IsDeleted = false,
                            Price = 15m,
                            Quantity = 10,
                            Title = "T-Shirt"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3961),
                            Description = "Stylish jeans",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIGQ4kPv_5xXW1c0A6Kek-gKYgz0v4QLI2LQ&s",
                            IsDeleted = false,
                            Price = 40m,
                            Quantity = 10,
                            Title = "Jeans"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3963),
                            Description = "Powerful blender",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_qRpeFbOBczwAvah7I1P6MTkVzU-voGfz4w&s",
                            IsDeleted = false,
                            Price = 55m,
                            Quantity = 30,
                            Title = "Blender"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3964),
                            Description = "Non-stick cookware set",
                            Image = "https://m.media-amazon.com/images/I/81JUxqQr4bL.jpg",
                            IsDeleted = false,
                            Price = 75m,
                            Quantity = 10,
                            Title = "Cookware Set"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3966),
                            Description = "Cool action figure",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSviqIY1yGnyOdSv2y6uUSFpag06SPk9KWcKg&s",
                            IsDeleted = false,
                            Price = 25m,
                            Quantity = 10,
                            Title = "Action Figure"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 30, 16, 31, 53, 561, DateTimeKind.Local).AddTicks(3967),
                            Description = "Fun board game",
                            Image = "https://www.lego.com/cdn/cs/set/assets/blt3a83606875d8dca3/40719_Box1_v39.png",
                            IsDeleted = false,
                            Price = 30m,
                            Quantity = 20,
                            Title = "Board Game"
                        });
                });

            modelBuilder.Entity("Shop.Entity.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shop.Entity.Entities.Cart", b =>
                {
                    b.HasOne("Shop.Entity.Entities.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.Entity.Entities.CartItem", b =>
                {
                    b.HasOne("Shop.Entity.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Entity.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Entity.Entities.Product", b =>
                {
                    b.HasOne("Shop.Entity.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.Entity.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Shop.Entity.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Shop.Entity.Entities.User", b =>
                {
                    b.Navigation("Carts");
                });
#pragma warning restore 612, 618
        }
    }
}
